services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229" # Debugging
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL=secret}
      - PORT=3000
  db:
    image: postgres:17
    restart: always
    environment:
      POSGRES_DB: ${POSTGRES_DB=secret}
      POSTGRES_USER: ${POSTGRES_USER=secret}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD=secret}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
