services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229" # Debugging
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/postgres
      - NODE_ENV=development
      - PORT=3000
  db:
    image: postgres:17
    restart: always
    environment:
      POSGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
